### ISSUE TITLE
Maybe the algo can optimize?

### ISSUE THREAD

**Issue by TCeason** [magiclen/boyer-moore-magiclen#3]
```rust
hello👆 git:(master) ⚡ cat src/main.rs
use std::time::Instant;
use boyer_moore_magiclen::BMByte;
/*
fn main() {
    let needle = (0..100).map(|_| "b").collect::<String>();
    let heystack = (0..100_000).map(|_| "a").collect::<String>();

    println!("Data ready.");

    let now = Instant::now();
    for _ in 0..1_000_000 {
        if heystack.find(&needle).is_some() { }
    }
    let ned = Instant::now();
    println!("cost:{:?}", ned-now);
}
*/
fn main() {
    let needle = (0..100).map(|_| "b").collect::<String>();
    let heystack = (0..100_000).map(|_| "a").collect::<String>();

    println!("Data ready.");

    let now = Instant::now();
    let bmb = BMByte::from(needle).unwrap();
    for _ in 0..1_000_000 {
        if bmb.find_first_in(&heystack).is_some() {}
    }
    let ned = Instant::now();
    println!("cost:{:?}", ned-now);
}

hello👆 git:(master) ⚡ cargo run -r   
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/hello`
Data ready.
cost:4.293501137s
```

On my local, std::find just cost 1.381615965s

**Comment by magiclen** [comment]
When the length of the needle is long enough, `boyer-moore-magiclen` would be faster than the naive search.

**Comment by TCeason** [comment]
> When the length of the needle is long enough, `boyer-moore-magiclen` would be faster than the naive search.

thx. BTW I see a algo Volnitsky str_search, it looks like a better search algo based on bm. 

in http://volnitsky.com/project/str_search/. But the website is 502.

Do you know about this?

**Comment by magiclen** [comment]
> Do you know about this?

No, I haven't seen that before.

If you are interested in improving the performance, any PR is welcome. An introduction of `boyer-moore-magiclen` is located at https://magiclen.org/boyer-moore-magiclen/ (in Chinese).
